from typing import Protocol


class DocumentStorePort(Protocol):
    """Abstraction over the relational data store."""

    async def save_document(self, doc: dict) -> str: ...
    async def get_document(self, doc_id: str) -> dict | None: ...
    async def list_documents(self, kb_id: str) -> list[dict]: ...
