from typing import Protocol

class DocumentStorePort(Protocol):
    """Abstraction over the relational data store."""

    def save_document(self, doc: dict) -> str: ...
    def get_document(self, doc_id: str) -> dict | None: ...
    def list_documents(self, kb_id: str) -> list[dict]: ...
