from typing import Protocol

class VectorStorePort(Protocol):
    """Abstraction over any vector database."""

    def add(self, texts: list[str], metadatas: list[dict]) -> None: ...
    def search(self, query: str, top_k: int = 5) -> list[dict]: ...
    def delete(self, ids: list[str]) -> None: ...
